version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: server
    env_file:
      - .env
    environment:
        WOW_IP: 0.0.0.0
        WOW_PORT: 8801
        WOW_LOGLEVEL: debug
        WOW_MAX_IT : 1000000
    ports:
      - '8081:8081'

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: client
    env_file:
      - .env
    environment:
        WOW_IP: server
        WOW_PORT: 8801
        WOW_CLIENT_REQUEST_NUMBER: 10000
        WOW_CLIENT_SEND_INTERVAL_MS: 1000
        WOW_MAX_IT: 1000000
    depends_on:
      - server

