# build stage
FROM golang as builder
COPY . /src
WORKDIR /src

ENV GO111MODULE=on
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /deploy/client ./cmd/client/main.go
# final stage
FROM scratch
WORKDIR /
COPY --from=builder /deploy/client .
EXPOSE 8081
ENTRYPOINT  [ "./client" ]
